# Colors section for Ashen
# https://github.com/ficd0/ashen.nvim

[colors.primary]
foreground = "#dfdbdc"
background = "#000000"
dim_foreground = "#000000"
bright_foreground = "#f4f3f3"

[colors.cursor]
text = "#13111b"
cursor = "#cac3c5"

[colors.vi_mode_cursor]
text = "#13111b"
cursor = "#cac3c5"

[colors.search.matches]
foreground = "#dfdbdc"
background = "#000000"

[colors.search.focused_match]
foreground = "#13111b"
background = "#dfa996"

[colors.hints.start]
foreground = "#917d77"
background = "#1f1d24"

[colors.hints.end]
foreground = "#7d6a6f"
background = "#000000"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#dfdbdc"
background = "#1f1d24"

[colors.selection]
text = "#dfdbdc"
background = "#000000"

[colors.normal]
black = "#100e0e"
red = "#933737"
green = "#d18f5e"
yellow = "#e0af68"
blue = "#4b6f7a"
magenta = "#a48096"
cyan = "#82787c"
white = "#cac3c5"

[colors.bright]
black = "#2e292a"
red = "#c44b4f"
green = "#ff9e3b"
yellow = "#ffc777"
blue = "#6895a3"
magenta = "#d09bc2"
cyan = "#a89da1"
white = "#f4f3f3"

[colors.dim]
black = "#2e292a"
red = "#933737"
green = "#d18f5e"
yellow = "#e0af68"
blue = "#4b6f7a"
magenta = "#a48096"
cyan = "#82787c"
white = "#cac3c5"
