[colors.primary]
background = "#282828"        # dark0
foreground = "#ebdbb2"        # light1 (fg1)
dim_foreground = "#a89984"    # light4
bright_foreground = "#fbf1c7" # light0 (fg0)

[colors.cursor]
text = "#282828"   # dark0
cursor = "#ebdbb2" # light1

[colors.vi_mode_cursor]
text = "#282828"
cursor = "#fabd2f" # bright_yellow (comum para modo comando)

[colors.search.matches]
foreground = "#282828" # dark0
background = "#fabd2f" # bright_yellow (Search)

[colors.search.focused_match]
foreground = "#282828"
background = "#fe8019" # bright_orange (IncSearch)

[colors.selection]
text = "#282828"
background = "#665c54" # dark3 (Visual selection)

[colors.normal]
black = "#282828"   # dark0
red = "#cc241d"     # neutral_red
green = "#98971a"   # neutral_green
yellow = "#d79921"  # neutral_yellow
blue = "#458588"    # neutral_blue
magenta = "#b16286" # neutral_purple
cyan = "#689d6a"    # neutral_aqua
white = "#a89984"   # light4

[colors.bright]
black = "#928374"   # gray
red = "#fb4934"     # bright_red
green = "#b8bb26"   # bright_green
yellow = "#fabd2f"  # bright_yellow
blue = "#83a598"    # bright_blue
magenta = "#d3869b" # bright_purple
cyan = "#8ec07c"    # bright_aqua
white = "#ebdbb2"   # light1

[[colors.indexed_colors]]
index = 16
color = "#fe8019" # bright_orange

[[colors.indexed_colors]]
index = 17
color = "#d65d0e" # neutral_orange
