[colors.primary]
background = "#000000"
foreground = "#f8f8f2"
dim_foreground = "#75715e"
bright_foreground = "#f8f8f2"

[colors.cursor]
text = "#000000"
cursor = "#f8f8f2"

[colors.vi_mode_cursor]
text = "#000000"
cursor = "#e6db74"

[colors.search.matches]
foreground = "#000000"
background = "#e6db74"

[colors.search.focused_match]
foreground = "#000000"
background = "#fd971f"

[colors.footer_bar]
foreground = "#f8f8f2"
background = "#272822"

[colors.hints.start]
foreground = "#000000"
background = "#e6db74"

[colors.hints.end]
foreground = "#f8f8f2"
background = "#75715e"

[colors.selection]
text = "#f8f8f2"
background = "#49483e"

[colors.normal]
black = "#272822"
red = "#f92672"
green = "#a6e22e"
yellow = "#e6db74"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f8f8f2"

[colors.bright]
black = "#75715e"
red = "#f92672"
green = "#a6e22e"
yellow = "#e6db74"
blue = "#66d9ef"
magenta = "#ae81ff"
cyan = "#a1efe4"
white = "#f9f8f5"
